name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'

    - name: Install npm@5
      run: npm install -g npm@5

    - name: Build and test
      run: |
        npm ci
        npm run build
        npm test
