name: UglifyJS Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install UglifyJS
        run: npm install uglify-js

      - name: Check for dist directory
        run: test -d dist || mkdir dist

      - name: Build
        run: npx uglifyjs public/js/source/config.js -o dist/file.min.js
