name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create dist directory
      run: mkdir -p dist

    - name: Minify JavaScript files
      run: uglifyjs src/*.js -o dist/app.min.js
