name: Increment Build Number

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different
  pull_request:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current build number
        id: get_build_number
        run: echo "::set-output name=build_number::$(grep -oP 'data-build-number="\K\d+' index.html)"

      - name: Increment build number
        id: increment_build_number
        run: echo "::set-output name=build_number::$((${{ steps.get_build_number.outputs.build_number }} + 1))"

      - name: Update HTML file with new build number
        run: sed -i 's/Version = 1.0."[^"]*"/data-build-number="${{ steps.increment_build_number.outputs.build_number }}"/' public/about.html

      - name: Commit changes
        run: |
          git add .
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -a -m "Increment build number to ${{ steps.increment_build_number.outputs.build_number }}"
          git push
