name: Obfuscate JavaScript Files
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Obfuscate JavaScript files
      run: npx uglify-js --output dist --compress --mangle -- js/*.js
