name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create build folder
      run: mkdir -p public/dist

    - name: Commit build folder
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add public/dist
        git commit -m "Add build folder"
        git push
