name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 9.x
      uses: actions/setup-node@v3
      with:
        node-version: '9.x'

    - name: Install npm@5
      run: npm install -g npm@5
    
    - name: Install jscrambler
      run: npm install jscrambler

    - name: Build and test
      run: |
        npm ci
        npm run build
        npm test
